Fix/linting components
chingu-voyages/v8-bears-team-14 pull request #2
Opened 2019-03-19 23:10 UTC by nikrb

linting the components directory.
There's still two issues in CartItem.js.

2019-03-20 19:04 UTC, nikrb commented
Anyone know what is wrong here?
```
<Link href={`/piece?id=${item._id}`} as={`/piece/${item._id}`}>
            <a
              style={{ textDecoration: 'none', height: '48px' }}
              target="_self"
              onClick={closeDrawer}
            >
              <Thumb src={`/static/uploads/${item.images[0].thumb}`} />
            </a>
          </Link>
```
linter says:
```
/home/nik/projects/chingu/voyage8/bears14/components/CartDrawer/CartItem.js
  29:13  error  Visible, non-interactive elements with click handlers must have at least one keyboard listener  jsx-a11y/click-events-have-key-events
  29:13  error  Static HTML elements with event handlers require a role                                         jsx-a11y/no-static-element-interactions
```

2019-03-20 20:11 UTC, g1st commented
I was trying to google it earlier but not successfully! Anyway, this passes linting so hooray. But probably there are some issue in wrapper component or I don't understand it correctly, but when you will load this locally you'll see while tab'ing opened cartDrawer it will focus around contents once and second keyDown on tab would close drawer (instead of focusing that link).
This rule is trying to make sure that this link(image thumb) is selectable somehow by keybord? Not sure how to fix it if true.

2019-03-20 20:16 UTC, g1st commented
Ahh, removing tabIndex from Drawer in CartDrawer would fix that and it would be the expected behaviour, but probably linter would moan about missing tabIndex in CartDrawer?

2019-03-20 20:22 UTC, nikrb commented
yes all linting fixes. first required a role (I used link) then linter said it had to be focus-able, hence the tabIndex

2019-03-26 18:40 UTC, zurda requested changes
LGTM, great work! Left a few comments

2019-03-26 18:40 UTC, zurda commented on components/CartDrawer/CartDrawer.js
>          buyItNow={false}
Are the curly braces needed here, or could we write this like so: `buyItNow=false`

2019-03-26 18:40 UTC, zurda commented on components/CartDrawer/CartDrawer.js
>            tabIndex={0}
I think tab index's value is a number. Isn't it sufficient to write: `tabIndex=0`?

2019-03-26 18:40 UTC, zurda commented on components/CartDrawer/CartItem.js
> +              tabIndex={0}
I think it could be written without the curly braces: `tabIndex=0`

2019-03-26 18:40 UTC, zurda commented on components/ContactForm.js
> +    if (emailSent) {
I think this is a little different from the original syntax. In the original, we check if `this.state.isSendingMail`, and if it is false -> we check if emailSent. 
It might not be necessary, but to make this equivalent to the original, I think line 112 should be `else if` rather than `if`.

2019-03-26 18:40 UTC, zurda commented on components/ContactForm.js
> +        <Paper className={classes.paper} elevation={3}>
I think elevation's value is a number, so the curly braces might not be necessary. I suspect `elevation=3` should suffice

2019-03-26 18:40 UTC, zurda commented on components/ContactForm.js
>              rows={4}
Similarly, rows={4} => rows=4

2019-03-26 18:40 UTC, zurda commented on components/Gallery/InstagramGallery.js
>          spacing={8}
similar to previous, spacing=8 should suffice

2019-03-26 18:40 UTC, zurda commented on components/Gallery/InstagramGallery.js
>              <GridListTile key={tile.id} cols={1}>
`cols={1}` => `cols=1`

2019-03-26 18:40 UTC, zurda commented on components/NavDrawer/NavDrawer.js
>              tabIndex={0}
I think tabIndex=0 should suffice

2019-03-26 19:30 UTC, nikrb commented on components/CartDrawer/CartDrawer.js
>          buyItNow={false}
I think the curly braces are required, but I'm guessing. Give it a go and see what happens :)

2019-03-26 19:34 UTC, nikrb commented on components/CartDrawer/CartDrawer.js
>            tabIndex={0}
I'm afraid I copied this from a work around on the linting site. I think our linter maybe a little over zealous, Dan makes a great point in this blog post https://overreacted.io/writing-resilient-components/

2019-03-26 19:36 UTC, nikrb commented on components/CartDrawer/CartItem.js
> +              tabIndex={0}
possibly ... gotta say we're just linting here though. Maybe worry about this later?

2019-03-26 19:38 UTC, zurda commented on components/CartDrawer/CartDrawer.js
>          buyItNow={false}
Spot on! Opps, I'm marking this resolved. Will double check the others as well. For some reason thought the component should identify a boolean without the curlies.

2019-03-26 19:39 UTC, nikrb commented on components/ContactForm.js
> +    if (emailSent) {
line 110 returns so I think this is a moot point?

2019-03-26 19:39 UTC, zurda commented on components/CartDrawer/CartItem.js
> +              tabIndex={0}
I apologise for my confusion - Just pulled the branch (which I should have done before hand) and will mark these resolved.

2019-03-26 19:40 UTC, zurda commented on components/CartDrawer/CartDrawer.js
>            tabIndex={0}
Sorry about this. I'm marking this resolved.

2019-03-26 19:43 UTC, zurda commented
@nikrb Sorry about that - as suggested, pulled the branch and got to see that my comments weren't necessary and inaccurate. I apologise for this. I blame the time a day :)

2019-03-26 19:43 UTC, zurda approved these changes

2019-03-26 19:46 UTC, nikrb commented
@zurda wow that was weird. One moment I was editing and the next poof, all gone lol. No worries. I think your comments were valid, just out of context given we're just fixing linting errors.
Don't apologise, keep commenting.

2019-03-27 08:16 UTC, zurda commented
Approved. @g1st , if you can review and approve - this will be ready to go :)

2019-03-27 08:23 UTC, merged

2019-03-27 12:00 UTC, g1st commented on components/NavBar.js
> -      toggleDrawer: this.toggleDrawer
Ooops, this breaks app now. After removing toggleDrawer function from state (default Navigation drawer's ant Cart drawer's states may be not needed), but then all this state is passed to Context Provider on line 162:
```javascript
<DrawerContext.Provider value={this.state}>
```

2019-03-27 14:09 UTC, g1st commented on components/NavBar.js
> -      toggleDrawer: this.toggleDrawer
I [see now](https://github.com/yannickcr/eslint-plugin-react/issues/1910) eslint gives here fasle positive.