Move authentication server into project
chingu-voyages/v8-bears-team-14 pull request #32
Opened 2019-03-22 17:33 UTC by g1st

I just simply dumped authentication server in project dir and now run both servers with `npm start dev:auth` script. Also created online mongodb cluster, whitlisted all IP's so when I'll share password _hopefully_ you will be able to log in. And after that you can use MongoDB Compass as GUI for that database. Not sure if everything will work and if I have approached this not in a silly way :) Anyway, as a temporary solution maybe will be fine?
p.s. Don't forget to `npm install`.

p.p.s. On a second thought, if we would like to have separate db each(and probably we should), maybe put all database string in secret variables or config file and connect to process.env.MONGO_URI? Code will be the same for all and separate database addresses will live on our machines.

2019-03-22 17:47 UTC, nikrb commented
agree with p.p.s.
deploy server can connect to mlab. I'd be careful what you are white listing.

2019-03-22 17:48 UTC, nikrb commented on authentication-server/config.js
> +  db: `mongodb+srv://jewellery:${MONGODB_PASS}@cluster0-kvzie.mongodb.net/dovile?retryWrites=true`,
personally, I would put whole connection string in .env

2019-03-22 17:51 UTC, nikrb commented on authentication-server/services/passport.js
> +const LocalStrategy = require('passport-local');
I don't remember using passport jwt with passport-local before. Passport usually passes a token in `connect_sid` off the top of my head, so not sure we need to pass another jwt? However I'm no expert, so if it works let's go with it :)

2019-03-22 17:53 UTC, nikrb submitted a review, later dismissed
LGTM though I would remove the db url from repo

2019-03-22 18:07 UTC, g1st commented
Like this?

2019-03-22 18:10 UTC, g1st commented on authentication-server/services/passport.js
> +const LocalStrategy = require('passport-local');
I think it works just fine and you are definitely more experienced on this than me, I just forked that repo and used for the project. Even readme there is not altered!

2019-03-23 16:02 UTC, nikrb submitted a review, later dismissed
LGTM

2019-03-26 19:06 UTC, zurda requested changes
LGTM, left a few questions/ queries but nothing too blocking IMO

2019-03-26 19:06 UTC, zurda commented on authentication-server/controllers/authentication.js
> +  User.findOne({ email: email }, function(err, existingUser) {
`{email: email}` =>  { email }

2019-03-26 19:06 UTC, zurda commented on authentication-server/controllers/authentication.js
> +      password: password
Could use shorthand here: 

```js
{
email,
password
}
```

2019-03-26 19:06 UTC, zurda commented on authentication-server/models/User.js
> +  password: String
Should we add a `required: true` to both email and password's schema?

2019-03-26 19:06 UTC, zurda commented on authentication-server/server.js
> +  console.log(`Server started on port  + ${port}`);
I think if we're using template literals, the `+` isn't necessary: 

`Server started on port: ${port}` should suffice

2019-03-26 19:06 UTC, zurda commented on authentication-server/services/passport.js
> +  User.findOne({ email: email }, function (err, user) {
`{ email: email }` => `{ email }`

2019-03-26 19:06 UTC, zurda commented on server.js
>  const PORT = 3000;
Could we get the port and the DB_URL from `authentication-server/config.js` to prevent duplicity?

2019-03-26 19:52 UTC, nikrb commented on server.js
>  const PORT = 3000;
we shouldn't put private stuff in the repo. Personally I would move config contents to .env.

2019-03-26 19:54 UTC, nikrb commented
@g1st I think @zurda has made some reasonable comments here. Let's discuss at the meeting whether we're going to let them slide for now as we're just trying to get it running locally. Surprised linter didn't complain.

2019-03-27 08:25 UTC, zurda commented on authentication-server/controllers/authentication.js
> +  User.findOne({ email: email }, function(err, existingUser) {
These were created because the linter didn't run. Marking this resolved.

2019-03-27 08:25 UTC, zurda commented on authentication-server/controllers/authentication.js
> +      password: password
These were created because the linter didn't run. Marking this resolved.

2019-03-27 08:25 UTC, zurda commented on authentication-server/services/passport.js
> +  User.findOne({ email: email }, function (err, user) {
This occurred since Linter didn't run.

2019-03-27 08:33 UTC, zurda commented on authentication-server/services/passport.js
> +const LocalStrategy = require('passport-local');
I'm marking this resolved for now

2019-03-27 08:44 UTC, zurda commented on authentication-server/config.js
> +  db: `mongodb+srv://jewellery:${MONGODB_PASS}@cluster0-kvzie.mongodb.net/dovile?retryWrites=true`,
This is marked outdated. I also tried to search for it in the repo but couldn't find it. I'm assuming this was handled in a different PR? Do you think we shuold mark this resolved? @nikrb / @g1st

2019-03-27 08:50 UTC, g1st commented
I'm just fixing this, pushing in few mins! :)

2019-03-27 09:09 UTC, g1st commented
I think there may be some conflicts for our prettier setups?

2019-03-27 09:12 UTC, zurda commented on authentication-server/server.js
> +const { PORT, MONGODB_URL } = process.env;
@g1st Do we need to require dotenv in this file before using it, or is it available across the project?

2019-03-27 09:41 UTC, g1st commented on authentication-server/server.js
> +const { PORT, MONGODB_URL } = process.env;
I cannot access private variables without requiring it here. Not sure if there is some place where it would be possible to require just once.

2019-03-27 09:46 UTC, zurda approved these changes

2019-03-27 09:46 UTC, zurda commented on authentication-server/server.js
> +const { PORT, MONGODB_URL } = process.env;
I'll add require dotenv to `server.js` then

2019-03-27 09:47 UTC, merged